deployment:
  tasks:
    - export DEPLOYPATH=/home/mtsntega/raport-app.mtsn1tegal.sch.id/
    - /bin/cp -R * $DEPLOYPATH


#     ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/svnvbkdl/rizalazky.engineer/
#     - /bin/cp -r * $DEPLOYPATH